### PR TITLE
perf: make signature verify/generate polkadotjs compatible

### PR DESCRIPTION
**Pull request by jarvis8x7b**
- make signature generate & verify polkadotjs compatible, which affects talisman, parity signer

### CODE REVIEW

**Review by camfairchild — APPROVED** [review]
Thanks for the PR!

**Review by roman-opentensor — APPROVED** [review]

**Comment by tobiashomie** [comment]
i get what this code does, but dont understand what it could be used for specifically

**Comment by jarvis8x7b** [comment]
@tobiashomie depending on different cases like proving ownership of a subnet, etc. you may be asked to use the `verify.py` and `generate.py` scripts but let's say your wallet is on a ledger connected via talisman. the only way for verification to pass is if you exported your seed phrase out, which has its risks. 

image

so ideally you don't export the seed phrase and instead just sign via polkadotjs. however, polkadotjs always wraps their data in a "<Bytes>message data</Bytes>" (see https://github.com/polkadot-js/extension/issues/1357) so your signature generated by any app using polkadotjs would never be compatible with the existing `verify.py` script. this PR allows whichever method of generating signature to work with the `verify.py` script

**Comment by tobiashomie** [comment]
thanks for your kind explanation @jarvis8x7b 
and appreciate the contribution

**Pull request merged**
